ALTER TABLE public.news ADD COLUMN IF NOT EXISTS rank INTEGER DEFAULT 0;
ALTER TABLE public.gallery_items ADD COLUMN IF NOT EXISTS rank INTEGER DEFAULT 0;
ALTER TABLE public.notices ADD COLUMN IF NOT EXISTS rank INTEGER DEFAULT 0;
